// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$add_bb.
logic [B:0] DEFAULT_add_bb_a0;

// For |default$add_carry.
logic DEFAULT_add_carry_a0;

// For |default$op_bb_sx.
logic DEFAULT_op_bb_sx_a0;

// For |default$result_add.
logic DEFAULT_result_add_a0;

// For |default$result_eq.
logic DEFAULT_result_eq_a0;

// For |default$result_lt.
logic DEFAULT_result_lt_a0;

// For |default$rs1_sx.
logic DEFAULT_rs1_sx_a0;


