// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$co_alu_bool_op.
logic [1:0] DEFAULT_co_alu_bool_op_a0;

// For |default$co_alu_cmp_eq.
logic DEFAULT_co_alu_cmp_eq_a0;

// For |default$co_alu_cmp_sig.
logic DEFAULT_co_alu_cmp_sig_a0;

// For |default$co_alu_rd_sel_0.
logic DEFAULT_co_alu_rd_sel_0_a0;

// For |default$co_alu_rd_sel_1.
logic DEFAULT_co_alu_rd_sel_1_a0;

// For |default$co_alu_rd_sel_2.
logic DEFAULT_co_alu_rd_sel_2_a0;

// For |default$co_alu_sub.
logic DEFAULT_co_alu_sub_a0;

// For |default$co_bne_or_bge.
logic DEFAULT_co_bne_or_bge_a0;

// For |default$co_branch_op.
logic DEFAULT_co_branch_op_a0;

// For |default$co_bufreg_clr_lsb.
logic DEFAULT_co_bufreg_clr_lsb_a0;

// For |default$co_bufreg_imm_en.
logic DEFAULT_co_bufreg_imm_en_a0;

// For |default$co_bufreg_rs1_en.
logic DEFAULT_co_bufreg_rs1_en_a0;

// For |default$co_bufreg_sh_signed.
logic DEFAULT_co_bufreg_sh_signed_a0;

// For |default$co_cond_branch.
logic DEFAULT_co_cond_branch_a0;

// For |default$co_csr_addr.
logic [1:0] DEFAULT_co_csr_addr_a0;

// For |default$co_csr_d_sel.
logic DEFAULT_co_csr_d_sel_a0;

// For |default$co_csr_en.
logic DEFAULT_co_csr_en_a0;

// For |default$co_csr_imm_en.
logic DEFAULT_co_csr_imm_en_a0;

// For |default$co_csr_mcause_en.
logic DEFAULT_co_csr_mcause_en_a0;

// For |default$co_csr_mie_en.
logic DEFAULT_co_csr_mie_en_a0;

// For |default$co_csr_mstatus_en.
logic DEFAULT_co_csr_mstatus_en_a0;

// For |default$co_csr_source.
logic [1:0] DEFAULT_co_csr_source_a0;

// For |default$co_ctrl_jal_or_jalr.
logic DEFAULT_co_ctrl_jal_or_jalr_a0;

// For |default$co_ctrl_mret.
logic DEFAULT_co_ctrl_mret_a0;

// For |default$co_ctrl_pc_rel.
logic DEFAULT_co_ctrl_pc_rel_a0;

// For |default$co_ctrl_utype.
logic DEFAULT_co_ctrl_utype_a0;

// For |default$co_dbus_en.
logic DEFAULT_co_dbus_en_a0;

// For |default$co_e_op.
logic DEFAULT_co_e_op_a0;

// For |default$co_ebreak.
logic DEFAULT_co_ebreak_a0;

// For |default$co_ext_funct3.
logic [2:0] DEFAULT_co_ext_funct3_a0;

// For |default$co_immdec_ctrl_0.
logic DEFAULT_co_immdec_ctrl_0_a0;

// For |default$co_immdec_ctrl_1.
logic DEFAULT_co_immdec_ctrl_1_a0;

// For |default$co_immdec_ctrl_2.
logic DEFAULT_co_immdec_ctrl_2_a0;

// For |default$co_immdec_ctrl_3.
logic DEFAULT_co_immdec_ctrl_3_a0;

// For |default$co_immdec_en_0.
logic DEFAULT_co_immdec_en_0_a0;

// For |default$co_immdec_en_1.
logic DEFAULT_co_immdec_en_1_a0;

// For |default$co_immdec_en_2.
logic DEFAULT_co_immdec_en_2_a0;

// For |default$co_immdec_en_3.
logic DEFAULT_co_immdec_en_3_a0;

// For |default$co_mdu_op.
logic DEFAULT_co_mdu_op_a0;

// For |default$co_mem_cmd.
logic DEFAULT_co_mem_cmd_a0;

// For |default$co_mem_half.
logic DEFAULT_co_mem_half_a0;

// For |default$co_mem_signed.
logic DEFAULT_co_mem_signed_a0;

// For |default$co_mem_word.
logic DEFAULT_co_mem_word_a0;

// For |default$co_mtval_pc.
logic DEFAULT_co_mtval_pc_a0;

// For |default$co_op_b_source.
logic DEFAULT_co_op_b_source_a0;

// For |default$co_rd_alu_en.
logic DEFAULT_co_rd_alu_en_a0;

// For |default$co_rd_csr_en.
logic DEFAULT_co_rd_csr_en_a0;

// For |default$co_rd_mem_en.
logic DEFAULT_co_rd_mem_en_a0;

// For |default$co_rd_op.
logic DEFAULT_co_rd_op_a0;

// For |default$co_sh_right.
logic DEFAULT_co_sh_right_a0;

// For |default$co_shift_op.
logic DEFAULT_co_shift_op_a0;

// For |default$co_two_stage_op.
logic DEFAULT_co_two_stage_op_a0;

// For |default$csr_op.
logic DEFAULT_csr_op_a0;

// For |default$csr_valid.
logic DEFAULT_csr_valid_a0;

// For |default$wb_en.
logic DEFAULT_wb_en_a0;

// For |default$wb_rdt.
logic [31:2] DEFAULT_wb_rdt_a0;


