//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 157

//_\SV
// SPDX-License-Identifier: ISC
`default_nettype none
module serv_immdec
  #(parameter SHARED_RFADDR_IMM_REGS = 1,
    parameter W = 1)
  (
      input wire              i_clk,
   //State
   input wire        i_cnt_en,
   input wire        i_cnt_done,
   //Control
   input wire [3:0]  i_immdec_en,
   input wire        i_csr_imm_en,
   input wire [3:0]  i_ctrl,
   output wire [4:0] o_rd_addr,
   output wire [4:0] o_rs1_addr,
   output wire [4:0] o_rs2_addr,
   //Data
   output wire [W-1:0] o_csr_imm,
   output wire [W-1:0] o_imm,
   //External
   input wire        i_wb_en,
   input wire [31:7] i_wb_rdt);

   // Clock alias for TL-Verilog
   wire clk = i_clk;

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$cnt_done.
logic DEFAULT_cnt_done_a0;

// For |default$cnt_en.
logic DEFAULT_cnt_en_a0;

// For |default$csr_imm.
logic [W-1:0] DEFAULT_csr_imm_a0;

// For |default$csr_imm_en.
logic DEFAULT_csr_imm_en_a0;

// For |default$ctrl.
logic [3:0] DEFAULT_ctrl_a0;

// For |default$imm.
logic [W-1:0] DEFAULT_imm_a0;

// For |default$imm31.
logic DEFAULT_imm31_n1,
      DEFAULT_imm31_a0;

// For |default$imm7.
logic DEFAULT_imm7_n1,
      DEFAULT_imm7_a0;

// For |default$imm_b11_b7.
logic [4:0] DEFAULT_imm_b11_b7_n1,
            DEFAULT_imm_b11_b7_a0;

// For |default$imm_b19_b12_b20.
logic [8:0] DEFAULT_imm_b19_b12_b20_n1,
            DEFAULT_imm_b19_b12_b20_a0;

// For |default$imm_b24_b20.
logic [4:0] DEFAULT_imm_b24_b20_n1,
            DEFAULT_imm_b24_b20_a0;

// For |default$imm_b30_b25.
logic [5:0] DEFAULT_imm_b30_b25_n1,
            DEFAULT_imm_b30_b25_a0;

// For |default$immdec_en.
logic [3:0] DEFAULT_immdec_en_a0;

// For |default$immdec_en_in.
logic [3:0] DEFAULT_immdec_en_in_a0;

// For |default$rd_addr_out.
logic [4:0] DEFAULT_rd_addr_out_a0;

// For |default$rs1_addr_out.
logic [4:0] DEFAULT_rs1_addr_out_a0;

// For |default$rs2_addr_out.
logic [4:0] DEFAULT_rs2_addr_out_a0;

// For |default$signbit.
logic DEFAULT_signbit_a0;

// For |default$wb_en.
logic DEFAULT_wb_en_a0;

// For |default$wb_rdt.
logic [31:7] DEFAULT_wb_rdt_a0;




   //
   // Scope: |default
   //

      // Staging of $imm31.
      always_ff @(posedge clk) DEFAULT_imm31_a0 <= DEFAULT_imm31_n1;

      // Staging of $imm7.
      always_ff @(posedge clk) DEFAULT_imm7_a0 <= DEFAULT_imm7_n1;

      // Staging of $imm_b11_b7.
      always_ff @(posedge clk) DEFAULT_imm_b11_b7_a0[4:0] <= DEFAULT_imm_b11_b7_n1[4:0];

      // Staging of $imm_b19_b12_b20.
      always_ff @(posedge clk) DEFAULT_imm_b19_b12_b20_a0[8:0] <= DEFAULT_imm_b19_b12_b20_n1[8:0];

      // Staging of $imm_b24_b20.
      always_ff @(posedge clk) DEFAULT_imm_b24_b20_a0[4:0] <= DEFAULT_imm_b24_b20_n1[4:0];

      // Staging of $imm_b30_b25.
      always_ff @(posedge clk) DEFAULT_imm_b30_b25_a0[5:0] <= DEFAULT_imm_b30_b25_n1[5:0];



// ---------- Generated Code Ends ----------
//_\TLV
   //_|default
      //_@0
         // SERV Immediate Decoder
         // Decodes and shifts immediate values from RISC-V instructions
         // Supports both bit-serial (W=1) and parallel (W=4) operation modes

         // Connect Verilog inputs:
         assign DEFAULT_cnt_en_a0 = i_cnt_en;
         assign DEFAULT_cnt_done_a0 = i_cnt_done;
         assign DEFAULT_csr_imm_en_a0 = i_csr_imm_en;
         assign DEFAULT_ctrl_a0[3:0] = i_ctrl;
         assign DEFAULT_wb_en_a0 = i_wb_en;
         assign DEFAULT_wb_rdt_a0[31:7] = i_wb_rdt;

         // Connect immdec_en input only when needed in shared case
         
         
         assign DEFAULT_immdec_en_in_a0[3:0] = i_immdec_en;
         
         

   //_\source wip.tlv 8   // Instantiated from wip.tlv, 209 as: m5+serv_immdec(/top)
      //_|default
         //_@0
            // Main immediate decoder logic
            // Handles parameterized width (W=1 bit-serial, W=4 parallel)
            // and shared/separate RF address register modes
   
            // Signal assignments for immediate decoder
   
            // W=1 case: bit-serial processing with immediate shift registers
            
            /* CSR immediates are always zero-extended, hence clear the signbit */
            assign DEFAULT_imm31_n1 = DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[31] : DEFAULT_imm31_a0;
            assign DEFAULT_signbit_a0 = DEFAULT_imm31_a0 & ! DEFAULT_csr_imm_en_a0;
            
            
   
            
            
                                                                                               
   
            
            
                       
                                
   
            
                                    
                                             
   
            
                        
                                 
   
            
                                    
                                             
   
            
                                              
                                                       
   
            
            
                                   
                                            
   
            
                                    
                                             
   
            
                                              
                                                       
   
            
            
                                   
                                            
   
            
                                    
                                             
   
            
            
                                         
                                                  
   
            
                                    
                                             
   
            
            
            
   
            // Immediate register assignments for W=1 case
            
   
            // Shared RF address and immediate registers case (SHARED_RFADDR_IMM_REGS=1)
            
            assign DEFAULT_immdec_en_a0[3:0] = DEFAULT_immdec_en_in_a0;
            assign DEFAULT_imm_b19_b12_b20_n1[8:0] = DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[19:12], DEFAULT_wb_rdt_a0[20]} :
                                      (DEFAULT_cnt_en_a0 & DEFAULT_immdec_en_a0[1]) ? {DEFAULT_ctrl_a0[3] ? DEFAULT_signbit_a0 : DEFAULT_imm_b24_b20_a0[0], DEFAULT_imm_b19_b12_b20_a0[8:1]} :
                                      DEFAULT_imm_b19_b12_b20_a0;
            assign DEFAULT_imm7_n1 = DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[7] :
                       DEFAULT_cnt_en_a0 ? DEFAULT_signbit_a0 :
                       DEFAULT_imm7_a0;
            assign DEFAULT_imm_b30_b25_n1[5:0] = DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[30:25] :
                                  (DEFAULT_cnt_en_a0 & DEFAULT_immdec_en_a0[3]) ? {DEFAULT_ctrl_a0[2] ? DEFAULT_imm7_a0 : DEFAULT_ctrl_a0[1] ? DEFAULT_signbit_a0 : DEFAULT_imm_b19_b12_b20_a0[0], DEFAULT_imm_b30_b25_a0[5:1]} :
                                  DEFAULT_imm_b30_b25_a0;
            assign DEFAULT_imm_b24_b20_n1[4:0] = DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[24:20] :
                                  (DEFAULT_cnt_en_a0 & DEFAULT_immdec_en_a0[2]) ? {DEFAULT_imm_b30_b25_a0[0], DEFAULT_imm_b24_b20_a0[4:1]} :
                                  DEFAULT_imm_b24_b20_a0;
            assign DEFAULT_imm_b11_b7_n1[4:0] = DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[11:7] :
                                 (DEFAULT_cnt_en_a0 & DEFAULT_immdec_en_a0[0]) ? {DEFAULT_imm_b30_b25_a0[0], DEFAULT_imm_b11_b7_a0[4:1]} :
                                 DEFAULT_imm_b11_b7_a0;
            
   
            
            
                                                                                            
   
            
                        
                                 
   
            
                                                                  
                                                           
                                                                    
   
            
                                   
                                            
   
            
                                       
                                                
            
            
   
            // Output logic assignments
            
            assign DEFAULT_csr_imm_a0[W-1:0] = DEFAULT_imm_b19_b12_b20_a0[4];
   
            
            assign DEFAULT_rs1_addr_out_a0[4:0] = DEFAULT_imm_b19_b12_b20_a0[8:4];
            assign DEFAULT_rs2_addr_out_a0[4:0] = DEFAULT_imm_b24_b20_a0;
            assign DEFAULT_rd_addr_out_a0[4:0]  = DEFAULT_imm_b11_b7_a0;
            
            
            
            
            
   
            assign DEFAULT_imm_a0[W-1:0] = DEFAULT_cnt_done_a0 ? DEFAULT_signbit_a0 : DEFAULT_ctrl_a0[0] ? DEFAULT_imm_b11_b7_a0[0] : DEFAULT_imm_b24_b20_a0[0];
            
            
            
            
            
            
   
            
                           
                           
                           
            
   //_\end_source

   // Connect Verilog outputs:
   //_|default
      //_@0
         assign o_csr_imm = DEFAULT_csr_imm_a0;
         assign o_imm = DEFAULT_imm_a0;
         assign o_rd_addr = DEFAULT_rd_addr_out_a0;
         assign o_rs1_addr = DEFAULT_rs1_addr_out_a0;
         assign o_rs2_addr = DEFAULT_rs2_addr_out_a0;

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
