//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 90

//_\SV
`default_nettype none
module serv_rf_ram_if
  #(//Data width. Adjust to preferred width of SRAM data interface
    parameter width=8,

    parameter W = 1,
    //Select reset strategy.
    // "MINI" for resetting minimally required FFs
    // "NONE" for relying on FFs having a defined value on startup
    parameter reset_strategy="MINI",

    //Number of CSR registers. These are allocated after the normal
    // GPR registers in the RAM.
    parameter csr_regs=4,

    //Internal parameters calculated from above values. Do not change
    parameter B=W-1,
    parameter raw=$clog2(32+csr_regs), //Register address width
    parameter l2w=$clog2(width), //log2 of width
    parameter aw=5+raw-l2w) //Address width
  (
   //SERV side
   input wire                   i_clk,
   input wire                   i_rst,
   input wire                   i_wreq,
   input wire                   i_rreq,
   output wire                   o_ready,
   input wire [raw-1:0]           i_wreg0,
   input wire [raw-1:0]           i_wreg1,
   input wire                   i_wen0,
   input wire                   i_wen1,
   input wire [B:0]           i_wdata0,
   input wire [B:0]           i_wdata1,
   input wire [raw-1:0]           i_rreg0,
   input wire [raw-1:0]           i_rreg1,
   output wire [B:0]           o_rdata0,
   output wire [B:0]           o_rdata1,
   //RAM side
   output wire [aw-1:0]           o_waddr,
   output wire [width-1:0] o_wdata,
   output wire                   o_wen,
   output wire [aw-1:0]           o_raddr,
   output wire                   o_ren,
   input wire [width-1:0]  i_rdata);

   // Clock and reset signals for TL-Verilog
   wire clk;
   wire reset;
   assign clk = i_clk;
   assign reset = i_rst;

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$o_raddr.
logic [aw - 1 : 0] DEFAULT_o_raddr_a0;

// For |default$o_rdata0.
logic [B : 0] DEFAULT_o_rdata0_a0;

// For |default$o_rdata1.
logic [B : 0] DEFAULT_o_rdata1_a0;

// For |default$o_ready.
logic DEFAULT_o_ready_a0;

// For |default$o_ren.
logic DEFAULT_o_ren_a0;

// For |default$o_waddr.
logic [aw - 1 : 0] DEFAULT_o_waddr_a0;

// For |default$o_wdata.
logic [width - 1 : 0] DEFAULT_o_wdata_a0;

// For |default$o_wen.
logic DEFAULT_o_wen_a0;

// For |default$rcnt.
logic [CMSB : 0] DEFAULT_rcnt_n1,
                 DEFAULT_rcnt_a0;

// For |default$rdata.
logic [width - 1 : 0] DEFAULT_rdata_a0;

// For |default$rdata0.
logic [width - 1 : 0] DEFAULT_rdata0_n1,
                      DEFAULT_rdata0_a0;

// For |default$rdata1.
logic [width - 1 - W : 0] DEFAULT_rdata1_n1,
                          DEFAULT_rdata1_a0;

// For |default$rgate.
logic DEFAULT_rgate_n1,
      DEFAULT_rgate_a0;

// For |default$rgnt.
logic DEFAULT_rgnt_n1,
      DEFAULT_rgnt_a0;

// For |default$rreg.
logic [raw - 1 : 0] DEFAULT_rreg_a0;

// For |default$rreg0.
logic [raw - 1 : 0] DEFAULT_rreg0_a0;

// For |default$rreg1.
logic [raw - 1 : 0] DEFAULT_rreg1_a0;

// For |default$rreq.
logic DEFAULT_rreq_a0;

// For |default$rreq_r.
logic DEFAULT_rreq_r_n1,
      DEFAULT_rreq_r_a0;

// For |default$rtrig0.
logic DEFAULT_rtrig0_a0;

// For |default$rtrig1.
logic DEFAULT_rtrig1_n1,
      DEFAULT_rtrig1_a0;

// For |default$wcnt.
logic [CMSB : 0] DEFAULT_wcnt_a0;

// For |default$wdata0.
logic [B : 0] DEFAULT_wdata0_a0;

// For |default$wdata0_r.
logic [width - 1 : 0] DEFAULT_wdata0_r_n1,
                      DEFAULT_wdata0_r_a0;

// For |default$wdata1.
logic [B : 0] DEFAULT_wdata1_a0;

// For |default$wdata1_r.
logic [width + W - 1 : 0] DEFAULT_wdata1_r_n1,
                          DEFAULT_wdata1_r_a0;

// For |default$wen0.
logic DEFAULT_wen0_a0;

// For |default$wen0_r.
logic DEFAULT_wen0_r_n1,
      DEFAULT_wen0_r_a0;

// For |default$wen1.
logic DEFAULT_wen1_a0;

// For |default$wen1_r.
logic DEFAULT_wen1_r_n1,
      DEFAULT_wen1_r_a0;

// For |default$wreg.
logic [raw - 1 : 0] DEFAULT_wreg_a0;

// For |default$wreg0.
logic [raw - 1 : 0] DEFAULT_wreg0_a0;

// For |default$wreg1.
logic [raw - 1 : 0] DEFAULT_wreg1_a0;

// For |default$wreq.
logic DEFAULT_wreq_a0;

// For |default$wtrig0.
logic DEFAULT_wtrig0_a0;

// For |default$wtrig1.
logic DEFAULT_wtrig1_a0;




   //
   // Scope: |default
   //

      // Staging of $rcnt.
      always_ff @(posedge clk) DEFAULT_rcnt_a0[CMSB : 0] <= DEFAULT_rcnt_n1[CMSB : 0];

      // Staging of $rdata0.
      always_ff @(posedge clk) DEFAULT_rdata0_a0[width - 1 : 0] <= DEFAULT_rdata0_n1[width - 1 : 0];

      // Staging of $rdata1.
      always_ff @(posedge clk) DEFAULT_rdata1_a0[width - 1 - W : 0] <= DEFAULT_rdata1_n1[width - 1 - W : 0];

      // Staging of $rgate.
      always_ff @(posedge clk) DEFAULT_rgate_a0 <= DEFAULT_rgate_n1;

      // Staging of $rgnt.
      always_ff @(posedge clk) DEFAULT_rgnt_a0 <= DEFAULT_rgnt_n1;

      // Staging of $rreq_r.
      always_ff @(posedge clk) DEFAULT_rreq_r_a0 <= DEFAULT_rreq_r_n1;

      // Staging of $rtrig1.
      always_ff @(posedge clk) DEFAULT_rtrig1_a0 <= DEFAULT_rtrig1_n1;

      // Staging of $wdata0_r.
      always_ff @(posedge clk) DEFAULT_wdata0_r_a0[width - 1 : 0] <= DEFAULT_wdata0_r_n1[width - 1 : 0];

      // Staging of $wdata1_r.
      always_ff @(posedge clk) DEFAULT_wdata1_r_a0[width + W - 1 : 0] <= DEFAULT_wdata1_r_n1[width + W - 1 : 0];

      // Staging of $wen0_r.
      always_ff @(posedge clk) DEFAULT_wen0_r_a0 <= DEFAULT_wen0_r_n1;

      // Staging of $wen1_r.
      always_ff @(posedge clk) DEFAULT_wen1_r_a0 <= DEFAULT_wen1_r_n1;



// ---------- Generated Code Ends ----------
//_\TLV
   // Connect Verilog inputs:
   //_|default
      //_@0
         assign DEFAULT_wreq_a0 = i_wreq;
         assign DEFAULT_wreg1_a0[raw - 1 : 0] = i_wreg1;
         assign DEFAULT_wreg0_a0[raw - 1 : 0] = i_wreg0;
         assign DEFAULT_wen0_a0 = i_wen0;
         assign DEFAULT_wen1_a0 = i_wen1;
         assign DEFAULT_wdata0_a0[B : 0] = i_wdata0;
         assign DEFAULT_wdata1_a0[B : 0] = i_wdata1;
         assign DEFAULT_rreg1_a0[raw - 1 : 0] = i_rreg1;
         assign DEFAULT_rreg0_a0[raw - 1 : 0] = i_rreg0;
         assign DEFAULT_rdata_a0[width - 1 : 0] = i_rdata;
         assign DEFAULT_rreq_a0 = i_rreq;
   //_\source wip.tlv 6   // Instantiated from wip.tlv, 159 as: m5+serv_rf_ram_if(/top)
      //_|default
         //_@0
            /*SV_plus*/
               localparam ratio = width / W;
               localparam CMSB = 4 - $clog2(W); //Counter MSB
               localparam l2r  = $clog2(ratio);
   
            /*
             ********** Write side ***********
             */
   
            // Write counter and trigger signals
            assign DEFAULT_wcnt_a0[CMSB : 0] = DEFAULT_rcnt_a0 - 4;
            assign DEFAULT_wtrig0_a0 = DEFAULT_rtrig1_a0;
   
            
            assign DEFAULT_wtrig1_a0 = DEFAULT_wcnt_a0[0];
            
            
            
   
            // Write data and address generation
            assign DEFAULT_o_wdata_a0[width - 1 : 0] = DEFAULT_wtrig1_a0 ? DEFAULT_wdata1_r_a0[width - 1 : 0] : DEFAULT_wdata0_r_a0;
   
            assign DEFAULT_wreg_a0[raw - 1 : 0] = DEFAULT_wtrig1_a0 ? DEFAULT_wreg1_a0 : DEFAULT_wreg0_a0;
            
            
            
            assign DEFAULT_o_waddr_a0[aw - 1 : 0] = {DEFAULT_wreg_a0, DEFAULT_wcnt_a0[CMSB : l2r]};
            
   
            assign DEFAULT_o_wen_a0 = (DEFAULT_wtrig0_a0 & DEFAULT_wen0_r_a0) | (DEFAULT_wtrig1_a0 & DEFAULT_wen1_r_a0);
   
            // Write control registers (sequential logic)
            
            
            
            assign DEFAULT_wen0_r_n1 = DEFAULT_wcnt_a0[0] ? DEFAULT_wen0_a0 : DEFAULT_wen0_r_a0;
            assign DEFAULT_wen1_r_n1 = DEFAULT_wcnt_a0[0] ? DEFAULT_wen1_a0 : DEFAULT_wen1_r_a0;
            assign DEFAULT_wdata0_r_n1[width - 1 : 0] = {DEFAULT_wdata0_a0, DEFAULT_wdata0_r_a0[width - 1 : W]};
            assign DEFAULT_wdata1_r_n1[width + W - 1 : 0] = {DEFAULT_wdata1_a0, DEFAULT_wdata1_r_a0[width + W - 1 : W]};
   
            /*
             ********** Read side ***********
             */
   
            // Read trigger and register selection
            assign DEFAULT_rtrig0_a0 = (DEFAULT_rcnt_a0[l2r - 1 : 0] == 1);
   
            assign DEFAULT_rreg_a0[raw - 1 : 0] = DEFAULT_rtrig0_a0 ? DEFAULT_rreg1_a0 : DEFAULT_rreg0_a0;
            
            
            
            assign DEFAULT_o_raddr_a0[aw - 1 : 0] = {DEFAULT_rreg_a0, DEFAULT_rcnt_a0[CMSB : l2r]};
            
   
            // Read data outputs
            assign DEFAULT_o_rdata0_a0[B : 0] = DEFAULT_rdata0_a0[B : 0];
            assign DEFAULT_o_rdata1_a0[B : 0] = DEFAULT_rtrig1_a0 ? DEFAULT_rdata_a0[B : 0] : DEFAULT_rdata1_a0[B : 0];
   
            
            assign DEFAULT_o_ren_a0 = DEFAULT_rgate_a0;
            
            
            
   
            assign DEFAULT_o_ready_a0 = DEFAULT_rgnt_a0 | DEFAULT_wreq_a0;
   
            // Read control registers (sequential logic)
            
            
            
            assign DEFAULT_rdata1_n1[width - 1 - W : 0] = DEFAULT_rtrig1_a0 ? DEFAULT_rdata_a0[W * 2 - 1 : W] : DEFAULT_rdata1_a0;
            
   
            // Main control registers
            assign DEFAULT_rtrig1_n1 = DEFAULT_rtrig0_a0;
            assign DEFAULT_rreq_r_n1 = (reset && (reset_strategy != "NONE")) ? 1'b0 : DEFAULT_rreq_a0;
            assign DEFAULT_rgnt_n1 = (reset && (reset_strategy != "NONE")) ? 1'b0 : DEFAULT_rreq_r_a0;
            assign DEFAULT_rdata0_n1[width - 1 : 0] = DEFAULT_rtrig0_a0 ? DEFAULT_rdata_a0 : {{W{1'b0}}, DEFAULT_rdata0_a0[width - 1 : W]};
            assign DEFAULT_rcnt_n1[CMSB : 0] = (reset && (reset_strategy != "NONE")) ? {CMSB + 1{1'b0}} :
                                 (DEFAULT_rreq_a0 | DEFAULT_wreq_a0) ? {{CMSB - 1{1'b0}}, DEFAULT_wreq_a0, 1'b0} : DEFAULT_rcnt_a0 + {{CMSB{1'b0}}, 1'b1};
            assign DEFAULT_rgate_n1 = (reset && (reset_strategy != "NONE")) ? 1'b0 :
                        (& DEFAULT_rcnt_a0 | DEFAULT_rreq_a0) ? DEFAULT_rreq_a0 : DEFAULT_rgate_a0;
   //_\end_source
   // Connect Verilog outputs:
   //_|default
      //_@0
         assign o_ready = DEFAULT_o_ready_a0;
         assign o_wdata = DEFAULT_o_wdata_a0;
         assign o_waddr = DEFAULT_o_waddr_a0;
         assign o_wen = DEFAULT_o_wen_a0;
         assign o_raddr = DEFAULT_o_raddr_a0;
         assign o_rdata0 = DEFAULT_o_rdata0_a0;
         assign o_rdata1 = DEFAULT_o_rdata1_a0;
         assign o_ren = DEFAULT_o_ren_a0;

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
