//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 3
//_\SV
// SPDX-License-Identifier: ISC
`default_nettype none
module serv_immdec
  #(parameter SHARED_RFADDR_IMM_REGS = 1,
    parameter W = 1)
  (
      input wire              i_clk,
   //State
   input wire        i_cnt_en,
   input wire        i_cnt_done,
   //Control
   input wire [3:0]  i_immdec_en,
   input wire        i_csr_imm_en,
   input wire [3:0]  i_ctrl,
   output wire [4:0] o_rd_addr,
   output wire [4:0] o_rs1_addr,
   output wire [4:0] o_rs2_addr,
   //Data
   output wire [W-1:0] o_csr_imm,
   output wire [W-1:0] o_imm,
   //External
   input wire        i_wb_en,
   input wire [31:7] i_wb_rdt);
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$imm31.
logic DEFAULT_imm31_n1,
      DEFAULT_imm31_a0;

// For |default$imm7.
logic DEFAULT_imm7_n1,
      DEFAULT_imm7_a0;

// For |default$imm_b11_b7.
logic [4:0] DEFAULT_imm_b11_b7_n1,
            DEFAULT_imm_b11_b7_a0;

// For |default$imm_b19_b12_b20.
logic [8:0] DEFAULT_imm_b19_b12_b20_n1,
            DEFAULT_imm_b19_b12_b20_a0;

// For |default$imm_b24_b20.
logic [4:0] DEFAULT_imm_b24_b20_n1,
            DEFAULT_imm_b24_b20_a0;

// For |default$imm_b30_b25.
logic [5:0] DEFAULT_imm_b30_b25_n1,
            DEFAULT_imm_b30_b25_a0;

// For |default$rd_addr_w1.
logic [4:0] DEFAULT_rd_addr_w1_n1,
            DEFAULT_rd_addr_w1_a0;

// For |default$rs1_addr_w1.
logic [4:0] DEFAULT_rs1_addr_w1_n1,
            DEFAULT_rs1_addr_w1_a0;

// For |default$rs2_addr_w1.
logic [4:0] DEFAULT_rs2_addr_w1_n1,
            DEFAULT_rs2_addr_w1_a0;

// For |default$signbit.
logic DEFAULT_signbit_a0;




   //
   // Scope: |default
   //

      // Staging of $imm31.
      always_ff @(posedge clk) DEFAULT_imm31_a0 <= DEFAULT_imm31_n1;

      // Staging of $imm7.
      always_ff @(posedge clk) DEFAULT_imm7_a0 <= DEFAULT_imm7_n1;

      // Staging of $imm_b11_b7.
      always_ff @(posedge clk) DEFAULT_imm_b11_b7_a0[4:0] <= DEFAULT_imm_b11_b7_n1[4:0];

      // Staging of $imm_b19_b12_b20.
      always_ff @(posedge clk) DEFAULT_imm_b19_b12_b20_a0[8:0] <= DEFAULT_imm_b19_b12_b20_n1[8:0];

      // Staging of $imm_b24_b20.
      always_ff @(posedge clk) DEFAULT_imm_b24_b20_a0[4:0] <= DEFAULT_imm_b24_b20_n1[4:0];

      // Staging of $imm_b30_b25.
      always_ff @(posedge clk) DEFAULT_imm_b30_b25_a0[5:0] <= DEFAULT_imm_b30_b25_n1[5:0];

      // Staging of $rd_addr_w1.
      always_ff @(posedge clk) DEFAULT_rd_addr_w1_a0[4:0] <= DEFAULT_rd_addr_w1_n1[4:0];

      // Staging of $rs1_addr_w1.
      always_ff @(posedge clk) DEFAULT_rs1_addr_w1_a0[4:0] <= DEFAULT_rs1_addr_w1_n1[4:0];

      // Staging of $rs2_addr_w1.
      always_ff @(posedge clk) DEFAULT_rs2_addr_w1_a0[4:0] <= DEFAULT_rs2_addr_w1_n1[4:0];



// ---------- Generated Code Ends ----------
//_\TLV
   //_|default
      //_@0
         // Pipesignal assignments
         
         assign DEFAULT_imm31_n1 = i_wb_en ? i_wb_rdt[31] : DEFAULT_imm31_a0;
         assign DEFAULT_signbit_a0 = DEFAULT_imm31_a0 & ! i_csr_imm_en;
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         

         // M5 conditional pipesignal assignments for W=1
         

         // Assignments for SHARED=1 case
         
         
                                   
                                   
         
                    
                    
         
                               
                               
         
                               
                               
         
                              
                              
         

         // Assignments for SHARED=0 case
         assign DEFAULT_rd_addr_w1_n1[4:0] = i_wb_en ? i_wb_rdt[11:7] : DEFAULT_rd_addr_w1_a0;
         assign DEFAULT_rs1_addr_w1_n1[4:0] = i_wb_en ? i_wb_rdt[19:15] : DEFAULT_rs1_addr_w1_a0;
         assign DEFAULT_rs2_addr_w1_n1[4:0] = i_wb_en ? i_wb_rdt[24:20] : DEFAULT_rs2_addr_w1_a0;

         assign DEFAULT_imm_b19_b12_b20_n1[8:0] = i_cnt_en ? {i_ctrl[3] ? DEFAULT_signbit_a0 : DEFAULT_imm_b24_b20_a0[0], DEFAULT_imm_b19_b12_b20_a0[8:1]} :
                                   i_wb_en ? {i_wb_rdt[19:12], i_wb_rdt[20]} :
                                   DEFAULT_imm_b19_b12_b20_a0;
         assign DEFAULT_imm7_n1 = i_cnt_en ? DEFAULT_signbit_a0 :
                    i_wb_en ? i_wb_rdt[7] :
                    DEFAULT_imm7_a0;
         assign DEFAULT_imm_b30_b25_n1[5:0] = i_cnt_en ? {i_ctrl[2] ? DEFAULT_imm7_a0 : i_ctrl[1] ? DEFAULT_signbit_a0 : DEFAULT_imm_b19_b12_b20_a0[0], DEFAULT_imm_b30_b25_a0[5:1]} :
                               i_wb_en ? i_wb_rdt[30:25] :
                               DEFAULT_imm_b30_b25_a0;
         assign DEFAULT_imm_b24_b20_n1[4:0] = i_cnt_en ? {DEFAULT_imm_b30_b25_a0[0], DEFAULT_imm_b24_b20_a0[4:1]} :
                               i_wb_en ? i_wb_rdt[24:20] :
                               DEFAULT_imm_b24_b20_a0;
         assign DEFAULT_imm_b11_b7_n1[4:0] = i_cnt_en ? {DEFAULT_imm_b30_b25_a0[0], DEFAULT_imm_b11_b7_a0[4:1]} :
                              i_wb_en ? i_wb_rdt[11:7] :
                              DEFAULT_imm_b11_b7_a0;
         
         

         /*SV_plus*/

            // Clock alias for TL-Verilog
            wire clk = i_clk;

            

               assign o_csr_imm = DEFAULT_imm_b19_b12_b20_a0[4];

                  
                     
                     
                     
                  
                     assign o_rd_addr  = DEFAULT_rd_addr_w1_a0;
                     assign o_rs1_addr = DEFAULT_rs1_addr_w1_a0;
                     assign o_rs2_addr = DEFAULT_rs2_addr_w1_a0;
                  

                  assign o_imm = i_cnt_done ? DEFAULT_signbit_a0 : i_ctrl[0] ? DEFAULT_imm_b11_b7_a0[0] : DEFAULT_imm_b24_b20_a0[0];
            














               
               
               
               
               
                  

                  









                  






                  




                  


               

               
                               
                               
                               
            

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
