//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 3
//_\SV
// SPDX-License-Identifier: ISC
`default_nettype none
module serv_immdec
  #(parameter SHARED_RFADDR_IMM_REGS = 1,
    parameter W = 1)
  (
      input wire              i_clk,
   //State
   input wire        i_cnt_en,
   input wire        i_cnt_done,
   //Control
   input wire [3:0]  i_immdec_en,
   input wire        i_csr_imm_en,
   input wire [3:0]  i_ctrl,
   output wire [4:0] o_rd_addr,
   output wire [4:0] o_rs1_addr,
   output wire [4:0] o_rs2_addr,
   //Data
   output wire [W-1:0] o_csr_imm,
   output wire [W-1:0] o_imm,
   //External
   input wire        i_wb_en,
   input wire [31:7] i_wb_rdt);
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$ii10.
logic DEFAULT_ii10_n1,
      DEFAULT_ii10_a0;

// For |default$ii11.
logic DEFAULT_ii11_n1,
      DEFAULT_ii11_a0;

// For |default$ii12.
logic DEFAULT_ii12_n1,
      DEFAULT_ii12_a0;

// For |default$ii13.
logic DEFAULT_ii13_n1,
      DEFAULT_ii13_a0;

// For |default$ii14.
logic DEFAULT_ii14_n1,
      DEFAULT_ii14_a0;

// For |default$ii15.
logic DEFAULT_ii15_n1,
      DEFAULT_ii15_a0;

// For |default$ii16.
logic DEFAULT_ii16_n1,
      DEFAULT_ii16_a0;

// For |default$ii17.
logic DEFAULT_ii17_n1,
      DEFAULT_ii17_a0;

// For |default$ii18.
logic DEFAULT_ii18_n1,
      DEFAULT_ii18_a0;

// For |default$ii19.
logic DEFAULT_ii19_n1,
      DEFAULT_ii19_a0;

// For |default$ii20.
logic DEFAULT_ii20_n1,
      DEFAULT_ii20_a0;

// For |default$ii20_b2.
logic DEFAULT_ii20_b2_n1,
      DEFAULT_ii20_b2_a0;

// For |default$ii21.
logic DEFAULT_ii21_n1,
      DEFAULT_ii21_a0;

// For |default$ii22.
logic DEFAULT_ii22_n1,
      DEFAULT_ii22_a0;

// For |default$ii23.
logic DEFAULT_ii23_n1,
      DEFAULT_ii23_a0;

// For |default$ii24.
logic DEFAULT_ii24_n1,
      DEFAULT_ii24_a0;

// For |default$ii25.
logic DEFAULT_ii25_n1,
      DEFAULT_ii25_a0;

// For |default$ii26.
logic DEFAULT_ii26_n1,
      DEFAULT_ii26_a0;

// For |default$ii27.
logic DEFAULT_ii27_n1,
      DEFAULT_ii27_a0;

// For |default$ii28.
logic DEFAULT_ii28_n1,
      DEFAULT_ii28_a0;

// For |default$ii29.
logic DEFAULT_ii29_n1,
      DEFAULT_ii29_a0;

// For |default$ii30.
logic DEFAULT_ii30_n1,
      DEFAULT_ii30_a0;

// For |default$ii31.
logic DEFAULT_ii31_n1,
      DEFAULT_ii31_a0;

// For |default$ii7.
logic DEFAULT_ii7_n1,
      DEFAULT_ii7_a0;

// For |default$ii7_b2.
logic DEFAULT_ii7_b2_n1,
      DEFAULT_ii7_b2_a0;

// For |default$ii8.
logic DEFAULT_ii8_n1,
      DEFAULT_ii8_a0;

// For |default$ii9.
logic DEFAULT_ii9_n1,
      DEFAULT_ii9_a0;

// For |default$rd_addr.
logic [4:0] DEFAULT_rd_addr_n1,
            DEFAULT_rd_addr_a0;

// For |default$rs1_addr.
logic [4:0] DEFAULT_rs1_addr_n1,
            DEFAULT_rs1_addr_a0;

// For |default$rs2_addr.
logic [4:0] DEFAULT_rs2_addr_n1,
            DEFAULT_rs2_addr_a0;

// For |default$signbit.
logic DEFAULT_signbit_a0;




   //
   // Scope: |default
   //

      // Staging of $ii10.
      always_ff @(posedge clk) DEFAULT_ii10_a0 <= DEFAULT_ii10_n1;

      // Staging of $ii11.
      always_ff @(posedge clk) DEFAULT_ii11_a0 <= DEFAULT_ii11_n1;

      // Staging of $ii12.
      always_ff @(posedge clk) DEFAULT_ii12_a0 <= DEFAULT_ii12_n1;

      // Staging of $ii13.
      always_ff @(posedge clk) DEFAULT_ii13_a0 <= DEFAULT_ii13_n1;

      // Staging of $ii14.
      always_ff @(posedge clk) DEFAULT_ii14_a0 <= DEFAULT_ii14_n1;

      // Staging of $ii15.
      always_ff @(posedge clk) DEFAULT_ii15_a0 <= DEFAULT_ii15_n1;

      // Staging of $ii16.
      always_ff @(posedge clk) DEFAULT_ii16_a0 <= DEFAULT_ii16_n1;

      // Staging of $ii17.
      always_ff @(posedge clk) DEFAULT_ii17_a0 <= DEFAULT_ii17_n1;

      // Staging of $ii18.
      always_ff @(posedge clk) DEFAULT_ii18_a0 <= DEFAULT_ii18_n1;

      // Staging of $ii19.
      always_ff @(posedge clk) DEFAULT_ii19_a0 <= DEFAULT_ii19_n1;

      // Staging of $ii20.
      always_ff @(posedge clk) DEFAULT_ii20_a0 <= DEFAULT_ii20_n1;

      // Staging of $ii20_b2.
      always_ff @(posedge clk) DEFAULT_ii20_b2_a0 <= DEFAULT_ii20_b2_n1;

      // Staging of $ii21.
      always_ff @(posedge clk) DEFAULT_ii21_a0 <= DEFAULT_ii21_n1;

      // Staging of $ii22.
      always_ff @(posedge clk) DEFAULT_ii22_a0 <= DEFAULT_ii22_n1;

      // Staging of $ii23.
      always_ff @(posedge clk) DEFAULT_ii23_a0 <= DEFAULT_ii23_n1;

      // Staging of $ii24.
      always_ff @(posedge clk) DEFAULT_ii24_a0 <= DEFAULT_ii24_n1;

      // Staging of $ii25.
      always_ff @(posedge clk) DEFAULT_ii25_a0 <= DEFAULT_ii25_n1;

      // Staging of $ii26.
      always_ff @(posedge clk) DEFAULT_ii26_a0 <= DEFAULT_ii26_n1;

      // Staging of $ii27.
      always_ff @(posedge clk) DEFAULT_ii27_a0 <= DEFAULT_ii27_n1;

      // Staging of $ii28.
      always_ff @(posedge clk) DEFAULT_ii28_a0 <= DEFAULT_ii28_n1;

      // Staging of $ii29.
      always_ff @(posedge clk) DEFAULT_ii29_a0 <= DEFAULT_ii29_n1;

      // Staging of $ii30.
      always_ff @(posedge clk) DEFAULT_ii30_a0 <= DEFAULT_ii30_n1;

      // Staging of $ii31.
      always_ff @(posedge clk) DEFAULT_ii31_a0 <= DEFAULT_ii31_n1;

      // Staging of $ii7.
      always_ff @(posedge clk) DEFAULT_ii7_a0 <= DEFAULT_ii7_n1;

      // Staging of $ii7_b2.
      always_ff @(posedge clk) DEFAULT_ii7_b2_a0 <= DEFAULT_ii7_b2_n1;

      // Staging of $ii8.
      always_ff @(posedge clk) DEFAULT_ii8_a0 <= DEFAULT_ii8_n1;

      // Staging of $ii9.
      always_ff @(posedge clk) DEFAULT_ii9_a0 <= DEFAULT_ii9_n1;

      // Staging of $rd_addr.
      always_ff @(posedge clk) DEFAULT_rd_addr_a0[4:0] <= DEFAULT_rd_addr_n1[4:0];

      // Staging of $rs1_addr.
      always_ff @(posedge clk) DEFAULT_rs1_addr_a0[4:0] <= DEFAULT_rs1_addr_n1[4:0];

      // Staging of $rs2_addr.
      always_ff @(posedge clk) DEFAULT_rs2_addr_a0[4:0] <= DEFAULT_rs2_addr_n1[4:0];



// ---------- Generated Code Ends ----------
//_\TLV
   //_|default
      //_@0
         // Pipesignal assignments
         
         
         
         
         assign DEFAULT_signbit_a0 = DEFAULT_ii31_a0 & ! i_csr_imm_en;
         assign DEFAULT_ii31_n1 = i_wb_en ? i_wb_rdt[31] : DEFAULT_ii31_a0;
         assign DEFAULT_ii30_n1 = i_cnt_en ? ((i_ctrl[1] | i_ctrl[2]) ? DEFAULT_signbit_a0 : DEFAULT_ii14_a0) : i_wb_en ? i_wb_rdt[30] : DEFAULT_ii30_a0;
         assign DEFAULT_ii29_n1 = i_cnt_en ? ((i_ctrl[1] | i_ctrl[2]) ? DEFAULT_signbit_a0 : DEFAULT_ii13_a0) : i_wb_en ? i_wb_rdt[29] : DEFAULT_ii29_a0;
         assign DEFAULT_ii28_n1 = i_cnt_en ? ((i_ctrl[1] | i_ctrl[2]) ? DEFAULT_signbit_a0 : DEFAULT_ii12_a0) : i_wb_en ? i_wb_rdt[28] : DEFAULT_ii28_a0;
         assign DEFAULT_ii27_n1 = i_cnt_en ? (i_ctrl[2] ? DEFAULT_ii7_a0 : i_ctrl[1] ? DEFAULT_signbit_a0 : DEFAULT_ii20_a0) : i_wb_en ? i_wb_rdt[27] : DEFAULT_ii27_a0;
         assign DEFAULT_ii26_n1 = i_cnt_en ? DEFAULT_ii30_a0 : i_wb_en ? i_wb_rdt[26] : DEFAULT_ii26_a0;
         assign DEFAULT_ii25_n1 = i_cnt_en ? DEFAULT_ii29_a0 : i_wb_en ? i_wb_rdt[25] : DEFAULT_ii25_a0;
         assign DEFAULT_ii23_n1 = i_cnt_en ? DEFAULT_ii27_a0 : i_wb_en ? i_wb_rdt[23] : DEFAULT_ii23_a0;
         assign DEFAULT_ii22_n1 = i_cnt_en ? DEFAULT_ii26_a0 : i_wb_en ? i_wb_rdt[22] : DEFAULT_ii22_a0;
         assign DEFAULT_ii21_n1 = i_cnt_en ? DEFAULT_ii25_a0 : i_wb_en ? i_wb_rdt[21] : DEFAULT_ii21_a0;
         assign DEFAULT_ii20_n1 = i_cnt_en ? DEFAULT_ii15_a0 : i_wb_en ? i_wb_rdt[20] : DEFAULT_ii20_a0;
         assign DEFAULT_ii19_n1 = i_cnt_en ? (i_ctrl[3] ? DEFAULT_signbit_a0 : DEFAULT_ii23_a0) : i_wb_en ? i_wb_rdt[19] : DEFAULT_ii19_a0;
         assign DEFAULT_ii18_n1 = i_cnt_en ? (i_ctrl[3] ? DEFAULT_signbit_a0 : DEFAULT_ii22_a0) : i_wb_en ? i_wb_rdt[18] : DEFAULT_ii18_a0;
         assign DEFAULT_ii17_n1 = i_cnt_en ? (i_ctrl[3] ? DEFAULT_signbit_a0 : DEFAULT_ii21_a0) : i_wb_en ? i_wb_rdt[17] : DEFAULT_ii17_a0;
         assign DEFAULT_ii15_n1 = i_cnt_en ? DEFAULT_ii19_a0 : i_wb_en ? i_wb_rdt[15] : DEFAULT_ii15_a0;
         assign DEFAULT_ii14_n1 = i_cnt_en ? DEFAULT_ii18_a0 : i_wb_en ? i_wb_rdt[14] : DEFAULT_ii14_a0;
         assign DEFAULT_ii13_n1 = i_cnt_en ? DEFAULT_ii17_a0 : i_wb_en ? i_wb_rdt[13] : DEFAULT_ii13_a0;
         assign DEFAULT_ii10_n1 = i_cnt_en ? DEFAULT_ii27_a0 : i_wb_en ? i_wb_rdt[10] : DEFAULT_ii10_a0;
         assign DEFAULT_ii9_n1 = i_cnt_en ? DEFAULT_ii26_a0 : i_wb_en ? i_wb_rdt[9] : DEFAULT_ii9_a0;
         assign DEFAULT_ii8_n1 = i_cnt_en ? DEFAULT_ii25_a0 : i_wb_en ? i_wb_rdt[8] : DEFAULT_ii8_a0;
         assign DEFAULT_ii7_n1 = i_cnt_en ? DEFAULT_signbit_a0 : i_wb_en ? i_wb_rdt[7] : DEFAULT_ii7_a0;
         assign DEFAULT_ii7_b2_n1 = i_cnt_en ? DEFAULT_ii11_a0 : i_wb_en ? i_wb_rdt[7] : DEFAULT_ii7_b2_a0;
         assign DEFAULT_ii20_b2_n1 = i_cnt_en ? DEFAULT_ii24_a0 : i_wb_en ? i_wb_rdt[20] : DEFAULT_ii20_b2_a0;
         assign DEFAULT_rd_addr_n1[4:0] = i_wb_en ? i_wb_rdt[11:7] : DEFAULT_rd_addr_a0;
         assign DEFAULT_rs1_addr_n1[4:0] = i_wb_en ? i_wb_rdt[19:15] : DEFAULT_rs1_addr_a0;
         assign DEFAULT_rs2_addr_n1[4:0] = i_wb_en ? i_wb_rdt[24:20] : DEFAULT_rs2_addr_a0;
         assign DEFAULT_ii12_n1 = i_cnt_en ? DEFAULT_ii16_a0 : i_wb_en ? i_wb_rdt[12] : DEFAULT_ii12_a0;
         assign DEFAULT_ii16_n1 = i_cnt_en ? (i_ctrl[3] ? DEFAULT_signbit_a0 : DEFAULT_ii20_b2_a0) : i_wb_en ? i_wb_rdt[16] : DEFAULT_ii16_a0;
         assign DEFAULT_ii24_n1 = i_cnt_en ? DEFAULT_ii28_a0 : i_wb_en ? i_wb_rdt[24] : DEFAULT_ii24_a0;
         assign DEFAULT_ii11_n1 = i_cnt_en ? DEFAULT_ii28_a0 : i_wb_en ? i_wb_rdt[11] : DEFAULT_ii11_a0;
         

         // M5 conditional pipesignal assignments for W=1
         

         
         
         
                                   
                                   
         
                    
                    
         
                               
                               
         
                               
                               
         
                              
                              
         

         
         
         
         

         
                                   
                                   
         
                    
                    
         
                               
                               
         
                               
                               
         
                              
                              
         
         

         /*SV_plus*/

            // Clock alias for TL-Verilog
            wire clk = i_clk;

            

               

                  
                     
                     
                     
                  
                     
                     
                     
                  

                  
            














               assign o_csr_imm = {DEFAULT_ii18_a0, DEFAULT_ii17_a0, DEFAULT_ii16_a0, DEFAULT_ii15_a0};
               assign o_rd_addr  = DEFAULT_rd_addr_a0;
               assign o_rs1_addr = DEFAULT_rs1_addr_a0;
               assign o_rs2_addr = DEFAULT_rs2_addr_a0;
               always @(posedge i_clk) begin
                  //Common - Initialization signals

                  //Bit lane 3









                  //Bit lane 2






                  //Bit lane 1




                  //Bit lane 0


               end

               assign o_imm = {(i_cnt_done ? DEFAULT_signbit_a0 : (i_ctrl[0] ? DEFAULT_ii10_a0 : DEFAULT_ii23_a0)),
                               i_ctrl[0] ? DEFAULT_ii9_a0 : DEFAULT_ii22_a0,
                               i_ctrl[0] ? DEFAULT_ii8_a0 : DEFAULT_ii21_a0,
                               i_ctrl[0] ? DEFAULT_ii7_b2_a0 : DEFAULT_ii20_b2_a0};
            

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
