// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$cc.
logic DEFAULT_cc_a0;

// For |default$cc_r.
logic [B:0] DEFAULT_cc_r_n1,
            DEFAULT_cc_r_a0;

// For |default$clr_lsb.
logic [B:0] DEFAULT_clr_lsb_a0;

// For |default$clr_lsb_internal.
logic [B:0] DEFAULT_clr_lsb_internal_a0;

// For |default$data.
logic [31:0] DEFAULT_data_n1,
             DEFAULT_data_a0;

// For |default$data_tail.
logic [W-2:0] DEFAULT_data_tail_n1,
              DEFAULT_data_tail_a0;

// For |default$lsb.
logic [1:0] DEFAULT_lsb_n1,
            DEFAULT_lsb_a0;

// For |default$lsb_w_eq_1.
logic [1:0] DEFAULT_lsb_w_eq_1_a0;

// For |default$muxdata.
logic [2 * W + B - 2:0] DEFAULT_muxdata_a0;

// For |default$muxout.
logic [B:0] DEFAULT_muxout_a0;

// For |default$qq.
logic [B:0] DEFAULT_qq_a0;

// For |default$qq_w_eq_1.
logic [B:0] DEFAULT_qq_w_eq_1_a0;

// For |default$qq_w_eq_4.
logic [B:0] DEFAULT_qq_w_eq_4_a0;

// For |default$shift_amount.
logic [2:0] DEFAULT_shift_amount_a0;




   //
   // Scope: |default
   //

      // Staging of $cc_r.
      always_ff @(posedge clk) DEFAULT_cc_r_a0[B:0] <= DEFAULT_cc_r_n1[B:0];

      // Staging of $data.
      always_ff @(posedge clk) DEFAULT_data_a0[31:0] <= DEFAULT_data_n1[31:0];

      // Staging of $data_tail.
      always_ff @(posedge clk) DEFAULT_data_tail_a0[W-2:0] <= DEFAULT_data_tail_n1[W-2:0];

      // Staging of $lsb.
      always_ff @(posedge clk) DEFAULT_lsb_a0[1:0] <= DEFAULT_lsb_n1[1:0];



