//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 3
//_\SV
`default_nettype none
module serv_rf_ram_if
  #(//Data width. Adjust to preferred width of SRAM data interface
    parameter width=8,

    parameter W = 1,
    //Select reset strategy.
    // "MINI" for resetting minimally required FFs
    // "NONE" for relying on FFs having a defined value on startup
    parameter reset_strategy="MINI",

    //Number of CSR registers. These are allocated after the normal
    // GPR registers in the RAM.
    parameter csr_regs=4,

    //Internal parameters calculated from above values. Do not change
    parameter B=W-1,
    parameter raw=$clog2(32+csr_regs), //Register address width
    parameter l2w=$clog2(width), //log2 of width
    parameter aw=5+raw-l2w) //Address width
  (
   //SERV side
   input wire                   i_clk,
   input wire                   i_rst,
   input wire                   i_wreq,
   input wire                   i_rreq,
   output wire                   o_ready,
   input wire [raw-1:0]           i_wreg0,
   input wire [raw-1:0]           i_wreg1,
   input wire                   i_wen0,
   input wire                   i_wen1,
   input wire [B:0]           i_wdata0,
   input wire [B:0]           i_wdata1,
   input wire [raw-1:0]           i_rreg0,
   input wire [raw-1:0]           i_rreg1,
   output wire [B:0]           o_rdata0,
   output wire [B:0]           o_rdata1,
   //RAM side
   output wire [aw-1:0]           o_waddr,
   output wire [width-1:0] o_wdata,
   output wire                   o_wen,
   output wire [aw-1:0]           o_raddr,
   output wire                   o_ren,
   input wire [width-1:0]  i_rdata);

   // Clock and reset signals for TL-Verilog
   wire clk;
   wire reset;
   assign clk = i_clk;
   assign reset = i_rst;

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$rreg.
logic [raw - 1 : 0] DEFAULT_rreg_a0;

// For |default$rtrig0.
logic DEFAULT_rtrig0_a0;

// For |default$wcnt.
logic [CMSB : 0] DEFAULT_wcnt_a0;

// For |default$wreg.
logic [raw - 1 : 0] DEFAULT_wreg_a0;

// For |default$wtrig0.
logic DEFAULT_wtrig0_a0;

// For |default$wtrig0_r.
logic DEFAULT_wtrig0_r_n1,
      DEFAULT_wtrig0_r_a0;

// For |default$wtrig1.
logic DEFAULT_wtrig1_a0;




   //
   // Scope: |default
   //

      // Staging of $wtrig0_r.
      always_ff @(posedge clk) DEFAULT_wtrig0_r_a0 <= DEFAULT_wtrig0_r_n1;



// ---------- Generated Code Ends ----------
//_\TLV
   //_|default
      //_@0
         assign o_ready = rgnt | i_wreq;
         assign DEFAULT_wcnt_a0[CMSB : 0] = rcnt - 4;
         assign DEFAULT_wtrig0_a0 = rtrig1;
         
         
         
         assign DEFAULT_wtrig1_a0 = DEFAULT_wtrig0_r_a0;
         
         assign DEFAULT_wreg_a0[raw - 1 : 0] = DEFAULT_wtrig1_a0 ? i_wreg1 : i_wreg0;
         assign o_wdata = DEFAULT_wtrig1_a0 ? wdata1_r[width - 1 : 0] : wdata0_r;
         
         
         
         assign o_waddr = {DEFAULT_wreg_a0, DEFAULT_wcnt_a0[CMSB : l2r]};
         
         assign o_wen = (DEFAULT_wtrig0_a0 & wen0_r) | (DEFAULT_wtrig1_a0 & wen1_r);
         assign DEFAULT_rtrig0_a0 = (rcnt[l2r - 1 : 0] == 1);
         assign DEFAULT_rreg_a0[raw - 1 : 0] = DEFAULT_rtrig0_a0 ? i_rreg1 : i_rreg0;
         
         
         
         assign o_raddr = {DEFAULT_rreg_a0, rcnt[CMSB : l2r]};
         
         assign o_rdata0 = rdata0[B : 0];
         assign o_rdata1 = rtrig1 ? i_rdata[B : 0] : rdata1[B : 0];
         
         
         
         assign o_ren = rgate & (rcnt[l2r - 1 : 1] == 0);
         
         assign DEFAULT_wtrig0_r_n1 = DEFAULT_wtrig0_a0;

         /*SV_plus*/   // YOU ARE HERE
            localparam ratio = width / W;
            localparam CMSB = 4 - $clog2(W); //Counter MSB
            localparam l2r  = $clog2(ratio);

            reg                                    rgnt;
            reg [CMSB : 0]           rcnt;

            reg                   rtrig1;
            /*
             ********** Write side ***********
             */

            reg [width - 1 : 0]   wdata0_r;
            reg [width + W - 1 : 0]   wdata1_r;

            reg                      wen0_r;
            reg                      wen1_r;

            always @(posedge clk) begin
               wen0_r    <= DEFAULT_wcnt_a0[0] ? i_wen0 : wen0_r;
               wen1_r    <= DEFAULT_wcnt_a0[0] ? i_wen1 : wen1_r;

               wdata0_r  <= {i_wdata0, wdata0_r[width - 1 : W]};
               wdata1_r  <= {i_wdata1, wdata1_r[width + W - 1 : W]};

            end

            /*
             ********** Read side ***********
             */

            reg [width - 1 : 0]  rdata0;
            reg [width - 1 - W : 0]  rdata1;

            reg                     rgate;

            reg               rreq_r;

            
            always @(posedge clk) begin
               // Combined assignment to eliminate split assignment
               rdata1 <= rtrig1 ? i_rdata[width - 1 : W] : {{W{1'b0}}, rdata1[width - W - 1 : W]};
            end
            
            
            

            always @(posedge clk) begin
               // Compound ternary expressions combining normal operation and reset
               rgate <= (reset && (reset_strategy != "NONE")) ? 1'b0 :
                        (& rcnt | i_rreq) ? i_rreq : rgate;

               rtrig1 <= DEFAULT_rtrig0_a0;

               rcnt <= (reset && (reset_strategy != "NONE")) ? {CMSB + 1{1'b0}} :
                       (i_rreq | i_wreq) ? {{CMSB - 1{1'b0}}, i_wreq, 1'b0} : rcnt + {{CMSB{1'b0}}, 1'b1};

               rreq_r <= (reset && (reset_strategy != "NONE")) ? 1'b0 : i_rreq;

               rgnt <= (reset && (reset_strategy != "NONE")) ? 1'b0 : rreq_r;

               rdata0 <= DEFAULT_rtrig0_a0 ? i_rdata : {{W{1'b0}}, rdata0[width - 1 : W]};
            end

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
