//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 157

//_\SV
// SPDX-License-Identifier: ISC
`default_nettype none
module serv_immdec
  #(parameter SHARED_RFADDR_IMM_REGS = 1,
    parameter W = 1)
  (
      input wire              i_clk,
   //State
   input wire        i_cnt_en,
   input wire        i_cnt_done,
   //Control
   input wire [3:0]  i_immdec_en,
   input wire        i_csr_imm_en,
   input wire [3:0]  i_ctrl,
   output wire [4:0] o_rd_addr,
   output wire [4:0] o_rs1_addr,
   output wire [4:0] o_rs2_addr,
   //Data
   output wire [W-1:0] o_csr_imm,
   output wire [W-1:0] o_imm,
   //External
   input wire        i_wb_en,
   input wire [31:7] i_wb_rdt);

   // Clock alias for TL-Verilog
   wire clk = i_clk;

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$cnt_done.
logic DEFAULT_cnt_done_a0;

// For |default$cnt_en.
logic DEFAULT_cnt_en_a0;

// For |default$csr_imm.
logic [W-1:0] DEFAULT_csr_imm_a0;

// For |default$csr_imm_en.
logic DEFAULT_csr_imm_en_a0;

// For |default$ctrl.
logic [3:0] DEFAULT_ctrl_a0;

// For |default$ii10.
logic DEFAULT_ii10_n1,
      DEFAULT_ii10_a0;

// For |default$ii11.
logic DEFAULT_ii11_n1,
      DEFAULT_ii11_a0;

// For |default$ii12.
logic DEFAULT_ii12_n1,
      DEFAULT_ii12_a0;

// For |default$ii13.
logic DEFAULT_ii13_n1,
      DEFAULT_ii13_a0;

// For |default$ii14.
logic DEFAULT_ii14_n1,
      DEFAULT_ii14_a0;

// For |default$ii15.
logic DEFAULT_ii15_n1,
      DEFAULT_ii15_a0;

// For |default$ii16.
logic DEFAULT_ii16_n1,
      DEFAULT_ii16_a0;

// For |default$ii17.
logic DEFAULT_ii17_n1,
      DEFAULT_ii17_a0;

// For |default$ii18.
logic DEFAULT_ii18_n1,
      DEFAULT_ii18_a0;

// For |default$ii19.
logic DEFAULT_ii19_n1,
      DEFAULT_ii19_a0;

// For |default$ii20.
logic DEFAULT_ii20_n1,
      DEFAULT_ii20_a0;

// For |default$ii20_b2.
logic DEFAULT_ii20_b2_n1,
      DEFAULT_ii20_b2_a0;

// For |default$ii21.
logic DEFAULT_ii21_n1,
      DEFAULT_ii21_a0;

// For |default$ii22.
logic DEFAULT_ii22_n1,
      DEFAULT_ii22_a0;

// For |default$ii23.
logic DEFAULT_ii23_n1,
      DEFAULT_ii23_a0;

// For |default$ii24.
logic DEFAULT_ii24_n1,
      DEFAULT_ii24_a0;

// For |default$ii25.
logic DEFAULT_ii25_n1,
      DEFAULT_ii25_a0;

// For |default$ii26.
logic DEFAULT_ii26_n1,
      DEFAULT_ii26_a0;

// For |default$ii27.
logic DEFAULT_ii27_n1,
      DEFAULT_ii27_a0;

// For |default$ii28.
logic DEFAULT_ii28_n1,
      DEFAULT_ii28_a0;

// For |default$ii29.
logic DEFAULT_ii29_n1,
      DEFAULT_ii29_a0;

// For |default$ii30.
logic DEFAULT_ii30_n1,
      DEFAULT_ii30_a0;

// For |default$ii31.
logic DEFAULT_ii31_n1,
      DEFAULT_ii31_a0;

// For |default$ii7.
logic DEFAULT_ii7_n1,
      DEFAULT_ii7_a0;

// For |default$ii7_b2.
logic DEFAULT_ii7_b2_n1,
      DEFAULT_ii7_b2_a0;

// For |default$ii8.
logic DEFAULT_ii8_n1,
      DEFAULT_ii8_a0;

// For |default$ii9.
logic DEFAULT_ii9_n1,
      DEFAULT_ii9_a0;

// For |default$imm.
logic [W-1:0] DEFAULT_imm_a0;

// For |default$rd_addr.
logic [4:0] DEFAULT_rd_addr_n1,
            DEFAULT_rd_addr_a0;

// For |default$rd_addr_out.
logic [4:0] DEFAULT_rd_addr_out_a0;

// For |default$rs1_addr.
logic [4:0] DEFAULT_rs1_addr_n1,
            DEFAULT_rs1_addr_a0;

// For |default$rs1_addr_out.
logic [4:0] DEFAULT_rs1_addr_out_a0;

// For |default$rs2_addr.
logic [4:0] DEFAULT_rs2_addr_n1,
            DEFAULT_rs2_addr_a0;

// For |default$rs2_addr_out.
logic [4:0] DEFAULT_rs2_addr_out_a0;

// For |default$signbit.
logic DEFAULT_signbit_a0;

// For |default$wb_en.
logic DEFAULT_wb_en_a0;

// For |default$wb_rdt.
logic [31:7] DEFAULT_wb_rdt_a0;




   //
   // Scope: |default
   //

      // Staging of $ii10.
      always_ff @(posedge clk) DEFAULT_ii10_a0 <= DEFAULT_ii10_n1;

      // Staging of $ii11.
      always_ff @(posedge clk) DEFAULT_ii11_a0 <= DEFAULT_ii11_n1;

      // Staging of $ii12.
      always_ff @(posedge clk) DEFAULT_ii12_a0 <= DEFAULT_ii12_n1;

      // Staging of $ii13.
      always_ff @(posedge clk) DEFAULT_ii13_a0 <= DEFAULT_ii13_n1;

      // Staging of $ii14.
      always_ff @(posedge clk) DEFAULT_ii14_a0 <= DEFAULT_ii14_n1;

      // Staging of $ii15.
      always_ff @(posedge clk) DEFAULT_ii15_a0 <= DEFAULT_ii15_n1;

      // Staging of $ii16.
      always_ff @(posedge clk) DEFAULT_ii16_a0 <= DEFAULT_ii16_n1;

      // Staging of $ii17.
      always_ff @(posedge clk) DEFAULT_ii17_a0 <= DEFAULT_ii17_n1;

      // Staging of $ii18.
      always_ff @(posedge clk) DEFAULT_ii18_a0 <= DEFAULT_ii18_n1;

      // Staging of $ii19.
      always_ff @(posedge clk) DEFAULT_ii19_a0 <= DEFAULT_ii19_n1;

      // Staging of $ii20.
      always_ff @(posedge clk) DEFAULT_ii20_a0 <= DEFAULT_ii20_n1;

      // Staging of $ii20_b2.
      always_ff @(posedge clk) DEFAULT_ii20_b2_a0 <= DEFAULT_ii20_b2_n1;

      // Staging of $ii21.
      always_ff @(posedge clk) DEFAULT_ii21_a0 <= DEFAULT_ii21_n1;

      // Staging of $ii22.
      always_ff @(posedge clk) DEFAULT_ii22_a0 <= DEFAULT_ii22_n1;

      // Staging of $ii23.
      always_ff @(posedge clk) DEFAULT_ii23_a0 <= DEFAULT_ii23_n1;

      // Staging of $ii24.
      always_ff @(posedge clk) DEFAULT_ii24_a0 <= DEFAULT_ii24_n1;

      // Staging of $ii25.
      always_ff @(posedge clk) DEFAULT_ii25_a0 <= DEFAULT_ii25_n1;

      // Staging of $ii26.
      always_ff @(posedge clk) DEFAULT_ii26_a0 <= DEFAULT_ii26_n1;

      // Staging of $ii27.
      always_ff @(posedge clk) DEFAULT_ii27_a0 <= DEFAULT_ii27_n1;

      // Staging of $ii28.
      always_ff @(posedge clk) DEFAULT_ii28_a0 <= DEFAULT_ii28_n1;

      // Staging of $ii29.
      always_ff @(posedge clk) DEFAULT_ii29_a0 <= DEFAULT_ii29_n1;

      // Staging of $ii30.
      always_ff @(posedge clk) DEFAULT_ii30_a0 <= DEFAULT_ii30_n1;

      // Staging of $ii31.
      always_ff @(posedge clk) DEFAULT_ii31_a0 <= DEFAULT_ii31_n1;

      // Staging of $ii7.
      always_ff @(posedge clk) DEFAULT_ii7_a0 <= DEFAULT_ii7_n1;

      // Staging of $ii7_b2.
      always_ff @(posedge clk) DEFAULT_ii7_b2_a0 <= DEFAULT_ii7_b2_n1;

      // Staging of $ii8.
      always_ff @(posedge clk) DEFAULT_ii8_a0 <= DEFAULT_ii8_n1;

      // Staging of $ii9.
      always_ff @(posedge clk) DEFAULT_ii9_a0 <= DEFAULT_ii9_n1;

      // Staging of $rd_addr.
      always_ff @(posedge clk) DEFAULT_rd_addr_a0[4:0] <= DEFAULT_rd_addr_n1[4:0];

      // Staging of $rs1_addr.
      always_ff @(posedge clk) DEFAULT_rs1_addr_a0[4:0] <= DEFAULT_rs1_addr_n1[4:0];

      // Staging of $rs2_addr.
      always_ff @(posedge clk) DEFAULT_rs2_addr_a0[4:0] <= DEFAULT_rs2_addr_n1[4:0];



// ---------- Generated Code Ends ----------
//_\TLV
   //_|default
      //_@0
         // SERV Immediate Decoder
         // Decodes and shifts immediate values from RISC-V instructions
         // Supports both bit-serial (W=1) and parallel (W=4) operation modes

         // Connect Verilog inputs:
         assign DEFAULT_cnt_en_a0 = i_cnt_en;
         assign DEFAULT_cnt_done_a0 = i_cnt_done;
         assign DEFAULT_csr_imm_en_a0 = i_csr_imm_en;
         assign DEFAULT_ctrl_a0[3:0] = i_ctrl;
         assign DEFAULT_wb_en_a0 = i_wb_en;
         assign DEFAULT_wb_rdt_a0[31:7] = i_wb_rdt;

         // Connect immdec_en input only when needed in shared case
         
         
         
         
         

   //_\source wip.tlv 8   // Instantiated from wip.tlv, 209 as: m5+serv_immdec(/top)
      //_|default
         //_@0
            // Main immediate decoder logic
            // Handles parameterized width (W=1 bit-serial, W=4 parallel)
            // and shared/separate RF address register modes
   
            // Signal assignments for immediate decoder
   
            // W=1 case: bit-serial processing with immediate shift registers
            
            
            
            
            
            assign DEFAULT_signbit_a0 = DEFAULT_ii31_a0 & ! DEFAULT_csr_imm_en_a0;
   
            // Common initialization for address registers
            assign {DEFAULT_ii31_n1, DEFAULT_rs2_addr_n1[4:0], DEFAULT_rs1_addr_n1[4:0], DEFAULT_rd_addr_n1[4:0]} = DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[31], DEFAULT_wb_rdt_a0[24:20], DEFAULT_wb_rdt_a0[19:15], DEFAULT_wb_rdt_a0[11:7]} :
                                                                                               {DEFAULT_ii31_a0, DEFAULT_rs2_addr_a0, DEFAULT_rs1_addr_a0, DEFAULT_rd_addr_a0};
   
            // Bit lane 3
            assign DEFAULT_ii7_n1 = DEFAULT_cnt_en_a0 ? DEFAULT_signbit_a0 :
                       DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[7] :
                                DEFAULT_ii7_a0;
   
            assign {DEFAULT_ii23_n1, DEFAULT_ii10_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii27_a0, DEFAULT_ii27_a0} :
                                    DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[23], DEFAULT_wb_rdt_a0[10]} :
                                             {DEFAULT_ii23_a0, DEFAULT_ii10_a0};
   
            assign DEFAULT_ii27_n1 = DEFAULT_cnt_en_a0 ? (DEFAULT_ctrl_a0[2] ? DEFAULT_ii7_a0 : DEFAULT_ctrl_a0[1] ? DEFAULT_signbit_a0 : DEFAULT_ii20_a0) :
                        DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[27] :
                                 DEFAULT_ii27_a0;
   
            assign {DEFAULT_ii20_n1, DEFAULT_ii15_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii15_a0, DEFAULT_ii19_a0} :
                                    DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[20], DEFAULT_wb_rdt_a0[15]} :
                                             {DEFAULT_ii20_a0, DEFAULT_ii15_a0};
   
            assign {DEFAULT_ii19_n1, DEFAULT_ii18_n1, DEFAULT_ii17_n1} = DEFAULT_cnt_en_a0 ? (DEFAULT_ctrl_a0[3] ? {DEFAULT_signbit_a0, DEFAULT_signbit_a0, DEFAULT_signbit_a0} : {DEFAULT_ii23_a0, DEFAULT_ii22_a0, DEFAULT_ii21_a0}) :
                                              DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[19], DEFAULT_wb_rdt_a0[18], DEFAULT_wb_rdt_a0[17]} :
                                                       {DEFAULT_ii19_a0, DEFAULT_ii18_a0, DEFAULT_ii17_a0};
   
            // Bit lane 2
            assign {DEFAULT_ii22_n1, DEFAULT_ii9_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii26_a0, DEFAULT_ii26_a0} :
                                   DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[22], DEFAULT_wb_rdt_a0[9]} :
                                            {DEFAULT_ii22_a0, DEFAULT_ii9_a0};
   
            assign {DEFAULT_ii26_n1, DEFAULT_ii14_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii30_a0, DEFAULT_ii18_a0} :
                                    DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[26], DEFAULT_wb_rdt_a0[14]} :
                                             {DEFAULT_ii26_a0, DEFAULT_ii14_a0};
   
            assign {DEFAULT_ii30_n1, DEFAULT_ii29_n1, DEFAULT_ii28_n1} = DEFAULT_cnt_en_a0 ? ((DEFAULT_ctrl_a0[1] | DEFAULT_ctrl_a0[2]) ? {DEFAULT_signbit_a0, DEFAULT_signbit_a0, DEFAULT_signbit_a0} : {DEFAULT_ii14_a0, DEFAULT_ii13_a0, DEFAULT_ii12_a0}) :
                                              DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[30], DEFAULT_wb_rdt_a0[29], DEFAULT_wb_rdt_a0[28]} :
                                                       {DEFAULT_ii30_a0, DEFAULT_ii29_a0, DEFAULT_ii28_a0};
   
            // Bit lane 1
            assign {DEFAULT_ii21_n1, DEFAULT_ii8_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii25_a0, DEFAULT_ii25_a0} :
                                   DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[21], DEFAULT_wb_rdt_a0[8]} :
                                            {DEFAULT_ii21_a0, DEFAULT_ii8_a0};
   
            assign {DEFAULT_ii25_n1, DEFAULT_ii13_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii29_a0, DEFAULT_ii17_a0} :
                                    DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[25], DEFAULT_wb_rdt_a0[13]} :
                                             {DEFAULT_ii25_a0, DEFAULT_ii13_a0};
   
            // Bit lane 0
            assign {DEFAULT_ii20_b2_n1, DEFAULT_ii7_b2_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii24_a0, DEFAULT_ii11_a0} :
                                         DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[20], DEFAULT_wb_rdt_a0[7]} :
                                                  {DEFAULT_ii20_b2_a0, DEFAULT_ii7_b2_a0};
   
            assign {DEFAULT_ii24_n1, DEFAULT_ii11_n1} = DEFAULT_cnt_en_a0 ? {DEFAULT_ii28_a0, DEFAULT_ii28_a0} :
                                    DEFAULT_wb_en_a0 ? {DEFAULT_wb_rdt_a0[24], DEFAULT_wb_rdt_a0[11]} :
                                             {DEFAULT_ii24_a0, DEFAULT_ii11_a0};
   
            assign DEFAULT_ii12_n1 = DEFAULT_cnt_en_a0 ? DEFAULT_ii16_a0 : DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[12] : DEFAULT_ii12_a0;
            assign DEFAULT_ii16_n1 = DEFAULT_cnt_en_a0 ? (DEFAULT_ctrl_a0[3] ? DEFAULT_signbit_a0 : DEFAULT_ii20_b2_a0) : DEFAULT_wb_en_a0 ? DEFAULT_wb_rdt_a0[16] : DEFAULT_ii16_a0;
            
   
            // Immediate register assignments for W=1 case
            
   
            
            
            
            
                                      
                                      
            
                       
                       
            
                                  
                                  
            
                                  
                                  
            
                                 
                                 
            
   
            
            
                                                                                            
   
            
                        
                                 
   
            
                                                                  
                                                           
                                                                    
   
            
                                   
                                            
   
            
                                       
                                                
            
            
   
            // Output logic assignments
            
            
   
            
            
            
            
            
            
            
            
            
   
            
            
            // W=4 case: parallel processing with individual bit registers
            assign DEFAULT_csr_imm_a0[W-1:0] = {DEFAULT_ii18_a0, DEFAULT_ii17_a0, DEFAULT_ii16_a0, DEFAULT_ii15_a0};
            assign DEFAULT_rd_addr_out_a0[4:0]  = DEFAULT_rd_addr_a0;
            assign DEFAULT_rs1_addr_out_a0[4:0] = DEFAULT_rs1_addr_a0;
            assign DEFAULT_rs2_addr_out_a0[4:0] = DEFAULT_rs2_addr_a0;
   
            assign DEFAULT_imm_a0[W-1:0] = {(DEFAULT_cnt_done_a0 ? DEFAULT_signbit_a0 : (DEFAULT_ctrl_a0[0] ? DEFAULT_ii10_a0 : DEFAULT_ii23_a0)),
                           DEFAULT_ctrl_a0[0] ? DEFAULT_ii9_a0 : DEFAULT_ii22_a0,
                           DEFAULT_ctrl_a0[0] ? DEFAULT_ii8_a0 : DEFAULT_ii21_a0,
                           DEFAULT_ctrl_a0[0] ? DEFAULT_ii7_b2_a0 : DEFAULT_ii20_b2_a0};
            
   //_\end_source

   // Connect Verilog outputs:
   //_|default
      //_@0
         assign o_csr_imm = DEFAULT_csr_imm_a0;
         assign o_imm = DEFAULT_imm_a0;
         assign o_rd_addr = DEFAULT_rd_addr_out_a0;
         assign o_rs1_addr = DEFAULT_rs1_addr_out_a0;
         assign o_rs2_addr = DEFAULT_rs2_addr_out_a0;

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
