//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 108

//_\SV
`default_nettype none
module serv_rf_if
  #(parameter WITH_CSR = 1,
    parameter W = 1,
    parameter B = W-1
  )
  (//RF Interface
   input wire                       i_cnt_en,
   output wire [4+WITH_CSR:0] o_wreg0,
   output wire [4+WITH_CSR:0] o_wreg1,
   output wire                       o_wen0,
   output wire                       o_wen1,
   output wire [B:0]  o_wdata0,
   output wire [B:0]  o_wdata1,
   output wire [4+WITH_CSR:0] o_rreg0,
   output wire [4+WITH_CSR:0] o_rreg1,
   input wire  [B:0] i_rdata0,
   input wire  [B:0] i_rdata1,

   //Trap interface
   input wire                       i_trap,
   input wire                       i_mret,
   input wire [B:0] i_mepc,
   input wire                      i_mtval_pc,
   input wire [B:0] i_bufreg_q,
   input wire [B:0] i_bad_pc,
   output wire [B:0] o_csr_pc,
   //CSR interface
   input wire                       i_csr_en,
   input wire [1:0]               i_csr_addr,
   input wire [B:0] i_csr,
   output wire [B:0] o_csr,
   //RD write port
   input wire                       i_rd_wen,
   input wire [4:0]               i_rd_waddr,
   input wire [B:0] i_ctrl_rd,
   input wire [B:0] i_alu_rd,
   input wire                       i_rd_alu_en,
   input wire [B:0] i_csr_rd,
   input wire                       i_rd_csr_en,
   input wire [B:0] i_mem_rd,
   input wire                       i_rd_mem_en,

   //RS1 read port
   input wire [4:0]               i_rs1_raddr,
   output wire [B:0] o_rs1,
   //RS2 read port
   input wire [4:0]               i_rs2_raddr,
   output wire [B:0] o_rs2);

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$alu_rd.
logic [B:0] DEFAULT_alu_rd_a0;

// For |default$cnt_en.
logic DEFAULT_cnt_en_a0;

// For |default$csr_out.
logic [B:0] DEFAULT_csr_out_a0;

// For |default$csr_pc_out.
logic [B:0] DEFAULT_csr_pc_out_a0;

// For |default$ctrl_rd.
logic [B:0] DEFAULT_ctrl_rd_a0;

// For |default$mem_rd.
logic [B:0] DEFAULT_mem_rd_a0;

// For |default$rd.
logic [B:0] DEFAULT_rd_a0;

// For |default$rd_alu_en.
logic DEFAULT_rd_alu_en_a0;

// For |default$rd_mem_en.
logic DEFAULT_rd_mem_en_a0;

// For |default$rd_waddr.
logic [4:0] DEFAULT_rd_waddr_a0;

// For |default$rd_wen.
logic DEFAULT_rd_wen_a0;

// For |default$rd_wen_in.
logic DEFAULT_rd_wen_in_a0;

// For |default$rdata0.
logic [B:0] DEFAULT_rdata0_a0;

// For |default$rdata1.
logic [B:0] DEFAULT_rdata1_a0;

// For |default$rreg0.
logic [4+WITH_CSR:0] DEFAULT_rreg0_a0;

// For |default$rreg1.
logic [4+WITH_CSR:0] DEFAULT_rreg1_a0;

// For |default$rs1_out.
logic [B:0] DEFAULT_rs1_out_a0;

// For |default$rs1_raddr.
logic [4:0] DEFAULT_rs1_raddr_a0;

// For |default$rs2_out.
logic [B:0] DEFAULT_rs2_out_a0;

// For |default$rs2_raddr.
logic [4:0] DEFAULT_rs2_raddr_a0;

// For |default$wdata0.
logic [B:0] DEFAULT_wdata0_a0;

// For |default$wdata1.
logic [B:0] DEFAULT_wdata1_a0;

// For |default$wen0.
logic DEFAULT_wen0_a0;

// For |default$wen1.
logic DEFAULT_wen1_a0;

// For |default$wreg0.
logic [4+WITH_CSR:0] DEFAULT_wreg0_a0;

// For |default$wreg1.
logic [4+WITH_CSR:0] DEFAULT_wreg1_a0;


// ---------- Generated Code Ends ----------
//_\TLV
   // Connect Verilog inputs:
   //_|default
      //_@0
         assign DEFAULT_cnt_en_a0 = i_cnt_en;
         assign DEFAULT_rdata0_a0[B:0] = i_rdata0;
         assign DEFAULT_rdata1_a0[B:0] = i_rdata1;
         assign DEFAULT_rd_wen_in_a0 = i_rd_wen;
         assign DEFAULT_rd_waddr_a0[4:0] = i_rd_waddr;
         assign DEFAULT_ctrl_rd_a0[B:0] = i_ctrl_rd;
         assign DEFAULT_alu_rd_a0[B:0] = i_alu_rd;
         assign DEFAULT_rd_alu_en_a0 = i_rd_alu_en;
         assign DEFAULT_mem_rd_a0[B:0] = i_mem_rd;
         assign DEFAULT_rd_mem_en_a0 = i_rd_mem_en;
         assign DEFAULT_rs1_raddr_a0[4:0] = i_rs1_raddr;
         assign DEFAULT_rs2_raddr_a0[4:0] = i_rs2_raddr;

         
         
         
         
         
         
         
         
         
         
         
         
         
         

   // Instantiate the TLV macro with the logic:
   //_\source wip.tlv 6   // Instantiated from wip.tlv, 194 as: m5+serv_rf_if_logic(/top)
      //_|default
         //_@0
            /*
             ********** Write side ***********
             */
   
            assign DEFAULT_rd_wen_a0 = DEFAULT_rd_wen_in_a0 & (|DEFAULT_rd_waddr_a0);
   
            
            
            
                
                
                
                                
   
            
   
            
            
   
            
             
             
             
             
             
             
             
             
             
   
            
            
   
            
            
   
            
             
             
   
            
            
   
            
   
            
             
             
   
             
             
             
             
   
             
             
   
             
             
             
             
   
             
             
            
            
                                    
                                    
   
            
            
            
            // NO_CSR configuration
            assign DEFAULT_rd_a0[B:0] = DEFAULT_ctrl_rd_a0 |
                DEFAULT_alu_rd_a0 & {W{DEFAULT_rd_alu_en_a0}} |
                DEFAULT_mem_rd_a0 & {W{DEFAULT_rd_mem_en_a0}};
   
            assign DEFAULT_wdata0_a0[B:0] = DEFAULT_rd_a0;
            assign DEFAULT_wdata1_a0[B:0] = {W{1'b0}};
   
            assign DEFAULT_wreg0_a0[4+WITH_CSR:0] = DEFAULT_rd_waddr_a0;
            assign DEFAULT_wreg1_a0[4+WITH_CSR:0] = 5'd0;
   
            assign DEFAULT_wen0_a0 = DEFAULT_cnt_en_a0 & DEFAULT_rd_wen_a0;
            assign DEFAULT_wen1_a0 = 1'b0;
   
            /*
             ********** Read side ***********
             */
   
            assign DEFAULT_rreg0_a0[4+WITH_CSR:0] = DEFAULT_rs1_raddr_a0;
            assign DEFAULT_rreg1_a0[4+WITH_CSR:0] = DEFAULT_rs2_raddr_a0;
   
            assign DEFAULT_csr_out_a0[B:0] = {W{1'b0}};
            assign DEFAULT_csr_pc_out_a0[B:0] = {W{1'b0}};
            
   
            // Common outputs
            assign DEFAULT_rs1_out_a0[B:0] = DEFAULT_rdata0_a0;
            assign DEFAULT_rs2_out_a0[B:0] = DEFAULT_rdata1_a0;
   //_\end_source

   // Connect Verilog outputs:
   //_|default
      //_@0
         assign o_wreg0 = DEFAULT_wreg0_a0;
         assign o_wreg1 = DEFAULT_wreg1_a0;
         assign o_wen0 = DEFAULT_wen0_a0;
         assign o_wen1 = DEFAULT_wen1_a0;
         assign o_wdata0 = DEFAULT_wdata0_a0;
         assign o_wdata1 = DEFAULT_wdata1_a0;
         assign o_rreg0 = DEFAULT_rreg0_a0;
         assign o_rreg1 = DEFAULT_rreg1_a0;
         assign o_rs1 = DEFAULT_rs1_out_a0;
         assign o_rs2 = DEFAULT_rs2_out_a0;
         assign o_csr = DEFAULT_csr_out_a0;
         assign o_csr_pc = DEFAULT_csr_pc_out_a0;

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
